# Generated by Django 5.2.7 on 2025-10-11 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('square', 'Square'), ('shopify', 'Shopify')], max_length=50, unique=True)),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
