# Generated by Django 5.2.7 on 2025-10-11 17:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0002_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='quantity_per_unit',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mscrInventory.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='mscrInventory.category'),
        ),
        migrations.CreateModel(
            name='RecipeModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('MILK', 'Milk'), ('FLAVOR', 'Flavor Shot'), ('SYRUP', 'Syrup'), ('SUGAR', 'Sugar'), ('EXTRA', 'Extra')], max_length=20)),
                ('base_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('size_multiplier', models.BooleanField(default=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mscrInventory.ingredient')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
    ]
