# Generated by Django 5.2.7 on 2025-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0003_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='products', to='mscrInventory.recipemodifier'),
        ),
    ]
