# Generated by Django 5.2.7 on 2025-10-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0004_product_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temperature_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('na', 'N/A')], default='na', max_length=10),
        ),
    ]
