# Generated by Django 5.2.7 on 2025-10-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0005_product_temperature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodifier',
            name='affects_type',
            field=models.CharField(blank=True, choices=[('MILK', 'Milk'), ('FLAVOR', 'Flavor Shot'), ('SYRUP', 'Syrup'), ('SUGAR', 'Sugar'), ('EXTRA', 'Extra')], help_text="For extras like 'Extra Flavor' or 'Drizzle Cup', specify which modifier type they affect.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipemodifier',
            name='expands_to',
            field=models.ManyToManyField(blank=True, help_text='For combo extras like Dirty Chai, specify which modifiers they expand to.', to='mscrInventory.recipemodifier'),
        ),
    ]
