# Generated by Django 5.2.7 on 2025-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0006_recipemodifier_affects_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('MILK', 'Milk'), ('FLAVOR', 'Flavor Shot'), ('SYRUP', 'Syrup'), ('SUGAR', 'Sugar'), ('EXTRA', 'Extra'), ('coffee', 'Coffee'), ('packaging', 'Packaging'), ('misc', 'Miscellaneous')], default='misc', help_text='Category of ingredient.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_type',
            field=models.CharField(choices=[('oz', 'Ounce'), ('lb', 'Pound'), ('fl_oz', 'Fluid Ounce'), ('unit', 'Unit/portion'), ('g', 'Gram'), ('kg', 'Kilogram')], default='unit', help_text='Unit of measurement for this ingredient.', max_length=16),
        ),
    ]
