# Generated by Django 5.2.7 on 2025-10-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscrInventory', '0007_ingredient_type_alter_ingredient_unit_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='mscrInventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(default='unit', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', True), _negated=True), name='recipeitem_product_required'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('ingredient__isnull', True), _negated=True), name='recipeitem_ingredient_required'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_ingredient_per_recipe'),
        ),
    ]
