# Generated by Django 5.2.7 on 2025-10-17 20:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0009_dynamic_types_seed_and_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unittype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="ingredienttype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ingredienttype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="conversion_to_base",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("1.0000"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="recipeitem_quantity_nonnegative",
            ),
        ),
    ]
