# Generated by Django 5.2.7 on 2025-10-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mscrInventory",
            "0010_alter_unittype_options_alter_ingredienttype_id_and_more",
        ),
    ]

    operations = []
