# Generated by Django 5.2.7 on 2025-10-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0011_schema_resync"),
    ]

    operations = []
