# Generated by Django 5.2.7 on 2025-10-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0012_confirm_recipemodifier_clean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipemodifier",
            name="affects_type",
        ),
        migrations.AlterField(
            model_name="recipemodifier",
            name="expands_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="For special modifiers that expand into multiple others. E.g., 'Dirty Chai' expands to [Espresso Shot, Chai Concentrate].",
                to="mscrInventory.recipemodifier",
            ),
        ),
        migrations.AlterField(
            model_name="recipemodifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("MILK", "Milk"),
                    ("FLAVOR", "Flavor Shot"),
                    ("SYRUP", "Syrup"),
                    ("SUGAR", "Sugar"),
                    ("EXTRA", "Extra"),
                    ("BAGEL", "Bagel"),
                    ("SPREAD", "Spread"),
                    ("TOPPING", "Topping"),
                    ("TOAST", "Toast"),
                    ("MUFFIN", "Muffin"),
                    ("BAKED_GOOD", "Baked Good"),
                    ("COFFEE", "Coffee"),
                    ("COOKIE", "Cookie"),
                ],
                max_length=20,
            ),
        ),
    ]
