# Generated by Django 5.2.7 on 2025-10-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0013_remove_recipemodifier_affects_type_and_more"),
    ]

    operations = []
