# Generated by Django 5.2.7 on 2025-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0014_schema_sync_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodifier",
            name="behavior",
            field=models.CharField(
                choices=[("add", "Add"), ("replace", "Replace"), ("scale", "Scale")],
                default="add",
                max_length=10,
            ),
        ),
    ]
