# Generated by Django 5.2.7 on 2025-10-24 21:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0015_recipemodifier_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="importlog",
            name="log_excerpt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipemodifier",
            name="quantity_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.0"),
                help_text="Multiplier applied to matching ingredients. Replaces size_multiplier.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="recipemodifier",
            name="replaces",
            field=models.JSONField(
                blank=True,
                help_text='Mapping of replacements for REPLACE behavior, e.g. {"to":[["Oat Milk",1.0]]}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipemodifier",
            name="target_selector",
            field=models.JSONField(
                blank=True,
                help_text='Filter for which ingredients this modifier affects, e.g. {"by_type":["MILK"],"by_name":["Bacon"]}',
                null=True,
            ),
        ),
    ]
