# Generated by Django 5.2.7 on 2025-10-24 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mscrInventory",
            "0016_importlog_log_excerpt_recipemodifier_quantity_factor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodifier",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipemodifier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
