# Generated by Django 5.2.7 on 2025-10-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0017_recipemodifier_created_at_recipemodifier_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ProductVariantCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(default="square", max_length=32)),
                (
                    "variant_name",
                    models.CharField(
                        help_text="Normalized variant descriptor (e.g., 'iced small')",
                        max_length=255,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional normalized details (e.g. {'temp': 'iced'})",
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_cache",
                        to="mscrInventory.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "platform", "variant_name")},
            },
        ),
    ]
