# Generated by Django 5.2.7 on 2025-10-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0018_orderitem_variant_info_productvariantcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mscrInventory.product",
                    ),
                ),
                (
                    "bag_size",
                    models.CharField(
                        choices=[
                            ("3oz", "3 oz sample"),
                            ("11oz", "11 oz bag"),
                            ("20oz", "20 oz bag"),
                            ("80oz", "5 lb bulk"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grind",
                    models.CharField(
                        choices=[
                            ("whole", "Whole Bean"),
                            ("drip", "Drip Grind (flat bottom filter)"),
                            ("espresso", "Espresso Grind"),
                            ("coarse", "Coarse Grind (French Press)"),
                            ("fine", "Fine Grind (cone filter)"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            bases=("mscrInventory.product",),
        ),
        migrations.AlterField(
            model_name="recipemodifier",
            name="behavior",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("replace", "Replace"),
                    ("scale", "Scale"),
                    ("expand", "Expand"),
                ],
                default="add",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipemodifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("MILK", "Milk"),
                    ("FLAVOR", "Flavor Shot"),
                    ("SYRUP", "Syrup"),
                    ("SUGAR", "Sugar"),
                    ("EXTRA", "Extra"),
                    ("BAGEL", "Bagel"),
                    ("SPREAD", "Spread"),
                    ("TOPPING", "Topping"),
                    ("TOAST", "Toast"),
                    ("MUFFIN", "Muffin"),
                    ("BAKED_GOOD", "Baked Good"),
                    ("COFFEE", "Coffee"),
                    ("COOKIE", "Cookie"),
                    ("COLD Foam", "Cold Foam"),
                ],
                max_length=20,
            ),
        ),
    ]
