# Generated by Django 5.2.7 on 2025-11-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0019_coffee_alter_recipemodifier_behavior_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoastProfile",
            fields=[
                (
                    "ingredient_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mscrInventory.ingredient",
                    ),
                ),
                (
                    "bag_size",
                    models.CharField(
                        choices=[
                            ("3oz", "3 oz sample"),
                            ("11oz", "11 oz bag"),
                            ("20oz", "20 oz bag"),
                            ("5lb", "5 lb bulk"),
                        ],
                        default="11oz",
                        max_length=10,
                    ),
                ),
                (
                    "grind",
                    models.CharField(
                        choices=[
                            ("whole", "Whole Bean"),
                            ("drip", "Drip Grind (flat bottom filter)"),
                            ("espresso", "Espresso Grind"),
                            ("coarse", "Coarse Grind (French Press)"),
                            ("fine", "Fine Grind (cone filter)"),
                        ],
                        default="whole",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roast Profile",
                "verbose_name_plural": "Roast Profiles",
            },
            bases=("mscrInventory.ingredient",),
        ),
        migrations.DeleteModel(
            name="Coffee",
        ),
    ]
