# Generated by Django 5.2.8 on 2025-11-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0025_importlog_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeModifierAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_label", models.CharField(max_length=150)),
                ("normalized_label", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="mscrInventory.recipemodifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Modifier Alias",
                "verbose_name_plural": "Recipe Modifier Aliases",
                "ordering": ["normalized_label"],
            },
        ),
    ]
