# Generated by Django 5.2.7 on 2025-11-11 21:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0026_recipemodifieralias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squareunmappeditem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=10)),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=4
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mscrInventory.unittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Type",
                "verbose_name_plural": "Container Types",
            },
        ),
        migrations.CreateModel(
            name="packaging",
            fields=[
                (
                    "ingredient_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mscrInventory.ingredient",
                    ),
                ),
                ("containerName", models.CharField(max_length=50, unique=True)),
                (
                    "temp",
                    models.CharField(
                        choices=[
                            ("hot", "hot"),
                            ("cold", "iced"),
                            ("both", "both"),
                            ("n/a", "n/a"),
                        ],
                        default="hot",
                        max_length=10,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mscrInventory.containertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packaging",
                "verbose_name_plural": "Packaging",
            },
            bases=("mscrInventory.ingredient",),
        ),
        migrations.CreateModel(
            name="PackagingSizeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("cold", "Cold"),
                            ("both", "Both"),
                            ("n/a", "N/A"),
                        ],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("size_label", models.CharField(max_length=20)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=6
                    ),
                ),
            ],
            options={
                "verbose_name": "Packaging Size Scale",
                "verbose_name_plural": "Packaging Size Scales",
                "unique_together": {("temperature", "size_label")},
            },
        ),
    ]
