# Generated by Django 5.2.7 on 2025-11-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mscrInventory",
            "0027_alter_squareunmappeditem_id_containertype_packaging_and_more",
        ),
    ]

    operations = []
