# Generated by Django 5.2.7 on 2025-11-11 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0028_schema_sync_checkpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packaging",
            name="containerName",
        ),
        migrations.AddField(
            model_name="packagingsizescale",
            name="packaging",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_scales",
                to="mscrInventory.packaging",
            ),
            preserve_default=False,
        ),
    ]
