# Generated by Django 5.2.7 on 2025-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0029_remove_packaging_containername_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("taster", "Taster"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("Large", "Large"),
                            ("XL", "XL"),
                            ("growler", "Growler"),
                            ("catering box", "Catering Box"),
                            ("keg", "Keg"),
                        ],
                        default="Hot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="packaging",
            name="multiplier",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="packaging",
            name="temp",
            field=models.CharField(
                choices=[
                    ("hot", "Hot"),
                    ("cold", "Iced"),
                    ("both", "Both"),
                    ("n/a", "N/A"),
                ],
                default="Hot",
            ),
        ),
        migrations.AddField(
            model_name="packaging",
            name="size_labels",
            field=models.ManyToManyField(
                blank=True, related_name="packagings", to="mscrInventory.sizelabel"
            ),
        ),
        migrations.DeleteModel(
            name="PackagingSizeScale",
        ),
    ]
