# Generated by Django 5.2.7 on 2025-11-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mscrInventory",
            "0030_sizelabel_packaging_multiplier_alter_packaging_temp_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="sizelabel",
            options={"ordering": ("label",)},
        ),
        migrations.AlterModelOptions(
            name="stockentry",
            options={
                "verbose_name": "Stock Entry",
                "verbose_name_plural": "Stock Entries",
            },
        ),
    ]
