# Generated by Django 5.2.7 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mscrInventory",
            "0031_alter_category_options_alter_sizelabel_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="packaging",
            name="expands_to",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__name__iexact": "packaging"},
                related_name="packaging_expanded_by",
                to="mscrInventory.ingredient",
            ),
        ),
    ]
