# Generated by Django 5.2.7 on 2025-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0032_packaging_expands_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packaging",
            name="expands_to",
        ),
        migrations.AddField(
            model_name="packaging",
            name="expands_to",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__name__iexact": "packaging"},
                related_name="packaging_expanded_by",
                symmetrical=False,
                to="mscrInventory.ingredient",
            ),
        ),
    ]
