# Generated by Django 5.2.8 on 2025-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mscrInventory", "0034_squareunmappeditem_last_raw_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="squareunmappeditem",
            name="item_type_hint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product", "Product"),
                    ("ingredient", "Ingredient"),
                    ("modifier", "Modifier"),
                ],
                help_text="Optional inference of whether the unmapped item looked like a modifier or ingredient.",
                max_length=32,
                null=True,
            ),
        ),
    ]
